version: '3'
services:
  freya:
    restart: always
    build: .
    ports:
      - "10000:10000"
    links:
      - minio

  minio:
    expose:
      - "9000"
    image: "minio/minio"
    restart: always
    command: "server /freyio"
    environment:
      MINIO_ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
      MINIO_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    ports:
      - "9000:9000"
    volumes:
      - freyio:/data

volumes:
  freyio: