---
port: 10000
sms:
  backend: "nexmo" # Now Only support Nexmo Backend
  endpoint: "https://rest.nexmo.com/sms/json"
  key: "${NEXMO_KEY}" # USe $ to extract from env variable
  secret: "${NEXMO_SECRET}"
mail:
  backend: "mailjet"
  server: "in-v3.mailjet.com"
  port: 587
  email: "${MAILJET_EMAIL}"
  password: "${MAILJET_PASSWORD}"
  metadata:
    from_name: "${SENDER_NAME}"
    from_email: "${SENDER_EMAIL}"
minio:
  endpoint: "minio:9000"